//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitcheelDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauseOfLossCode
    {
        public byte id { get; set; }
        public string cause { get; set; }
    }
}
