//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitcheelDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LossInfo
    {
        public long id { get; set; }
        public Nullable<long> mitcheelclaim_id { get; set; }
        public Nullable<int> iCauseOfLoss { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public string LossDescription { get; set; }
    
        public virtual MitchellClaim MitchellClaim { get; set; }
    }
}
