//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitcheelDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitchellClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MitchellClaim()
        {
            this.LossInfoes = new HashSet<LossInfo>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public long id { get; set; }
        public string claimNumber { get; set; }
        public string claimantFirstName { get; set; }
        public string caimantLastName { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> lossdate { get; set; }
        public Nullable<int> AssignedAdjusterID { get; set; }
    
        public virtual StatusCode StatusCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LossInfo> LossInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
