//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitcheelDBEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MitchellEntities : DbContext
    {
        public MitchellEntities()
            : base("name=MitchellEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CauseOfLossCode> CauseOfLossCodes { get; set; }
        public virtual DbSet<MitchellClaim> MitchellClaims { get; set; }
        public virtual DbSet<StatusCode> StatusCodes { get; set; }
        public virtual DbSet<LossInfo> LossInfoes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
