//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitcheelDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public long id { get; set; }
        public Nullable<long> mitcheelclaim_id { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public string MakeDescription { get; set; }
        public string ModelDescription { get; set; }
        public string EngineDescription { get; set; }
        public string ExteriorColor { get; set; }
        public string Vin { get; set; }
        public string LicPlate { get; set; }
        public string LicPlateState { get; set; }
        public Nullable<System.DateTime> LicPlateExpDate { get; set; }
        public string DamageDescription { get; set; }
        public Nullable<int> Mileage { get; set; }
    
        public virtual MitchellClaim MitchellClaim { get; set; }
    }
}
